In [1]:
#Install Tensor flow
!pip install -q tensorflow==2.0.beta1

     |████████████████████████████████| 87.9MB 61kB/s 
     |████████████████████████████████| 501kB 45.8MB/s 
     |████████████████████████████████| 3.1MB 29.2MB/s 


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [0]:
from tensorflow.keras.layers import SimpleRNN, Input, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam, SGD

# **Manual Calculation in RNN**
Things you should automatically know and have memorized
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [0]:
# Make some Data
N=1
T=10
D=3
K=2
X=np.random.randn(N, T, D)

In [0]:
# Make an RNN
M = 5 #No of Hidden units
i = Input(shape=(T,D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)
model = Model(i, x)

In [29]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

[[-1.2300607 -1.4270436]]


In [30]:
# See if we can replicate this output
# Get the weights first
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_4 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [31]:
#See what return
model.layers[1].get_weights()

[array([[ 0.08523887,  0.72808236,  0.33629614,  0.6538268 ,  0.49523133],
        [-0.28855902, -0.4479399 ,  0.821178  ,  0.46814424,  0.39328295],
        [ 0.7067159 ,  0.00110775,  0.6381294 ,  0.5845991 ,  0.22886938]],
       dtype=float32),
 array([[-0.07412553,  0.66545963, -0.1932038 ,  0.71687263,  0.02084737],
        [ 0.16917661, -0.33444053, -0.89721704,  0.07975746,  0.2194749 ],
        [-0.888713  , -0.13480288, -0.00863074,  0.0181849 ,  0.4377351 ],
        [ 0.3904159 , -0.27002192,  0.3789974 ,  0.37276977,  0.7014751 ],
        [-0.15378246, -0.59517163,  0.11815464,  0.58347607, -0.51741356]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [32]:
# Check their shapes
# Should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [0]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [34]:
h_last = np.zeros(M) # initial hidden state #h0
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h_t = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h_t.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  # important: assign h to h_last
  h_last = h_t

# print the final output
print(Yhats[-1])

[-1.23006078 -1.42704355]


In [0]:
## Calculate the output for multiple samples at once (N > 1)
N=5
T=10
D=3
K=2
X=np.random.randn(N, T, D)

In [0]:
# Make an RNN
M = 5 #No of Hidden units
i = Input(shape=(T,D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)
model = Model(i, x)

In [73]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

[[-0.10732634  0.21619698]
 [-0.12791099  0.7216065 ]
 [-0.18397862  0.10532055]
 [ 1.0536554  -0.05166629]
 [-1.0829895  -0.10941304]]


In [0]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [83]:
h_last = np.zeros(M) # initial hidden state #h0
x = X[1]
Yhats = [] # where we store the outputs

for t in range(T):
  h_t = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h_t.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  # important: assign h to h_last
  h_last = h_t



# print the final output
print(Yhats[-1])

[-0.12791099  0.72160658]
